### ISSUE TITLE
addon tab is displayed wrong on ff45

### ISSUE THREAD

**Issue by mausalimi** [AddonLab/AiOS#102]
it seems mozilla broke it again... the addon tab looks not like it is supposed to.

AIOS activated
![aios](https://cloud.githubusercontent.com/assets/1296426/13531642/ebc95392-e227-11e5-8a0a-b18fbce94a17.png)

AIOS deactivated
![noaios](https://cloud.githubusercontent.com/assets/1296426/13531651/f7a52574-e227-11e5-83da-ec6f5507d7bf.png)

oh boy... mozilla just doesn't care about extension developers or users.

**Comment by mausalimi** [comment]
ok, as a cheap workaround i did set 

dom.compartment_per_addon

to false, as it was in previous ff versions.

**Comment by ingowennemaring** [comment]
Sorry, but I don't know what you  exactly mean. Of course the addon panel looks different when AiOS is enabled, it's just improved for the sidebar. ;-) 

What do you think is wrong when AiOS is enabled?

**Comment by RDL-github** [comment]
Dear Ingo

I also see this as follows:

Firefox 45.0.1 x64 in Win 7 SP1 x64

Create virgin profile - No changes, no additions.
Install AiOS 0.7.28 - default settings.

AiOS 'Add-ons' button opens Add-ons in sidebar. OK.

In AiOS Options -> Panels -> Add-ons DISABLE/untick/uncheck 'Open in Sidebar'

Restart Firefox.

Click on Add-ons button on sidebar.

Then, as expected, the add-ons panel is displayed in a tab but, **instead of the expected format** (with buttons in a sidebar within that tab)

it uses the format normally displayed in the AiOS sidebar as in mausalimi's first screenshot.

When AiOS is installed but it is set to display Add-ons in a tab, I would expect the 'standard' format, as in mausalimi's second screenshot, to be used.

As mausalimi reported, with AiOS set for Add-ons to be displayed in a tab, if FF pref 'dom.compartment_per_addon' is changed to 'false' (which is not the FF45.0.1 default) and FF is reloaded, then, when displayed, that tab is correctly formatted as in mausalimi's second screenshot.

If 'dom.compartment_per_addon' is restored to 'true' (the FF45.0.1 default) and FF is reloaded, then, when displayed, that tab is incorrectly formatted as in mausalimi's first screenshot.

VBRR

**Comment by wooowooo** [comment]
I have the same problem!
After I upgraded firefox from 38 to 45, this problem occured.

**Comment by noahfriedman** [comment]
I'm seeing the same behavior RDL-github observed when I use AiOS 0.7.28 with Firefox 47.0 on linux.

The sidebar-optimized version of the add-ons page should not be "optimized" when it's displayed in a tab.

**Comment by reallyuniquename** [comment]
Same here. I'm on FF45, latest AiOS somehow affects about:addons page opened in tab (_not_ inside sidebar).

**Comment by ingowennemaring** [comment]
Fixed in the next release.

**Comment by RDL-github** [comment]
Fixed for me by AiOS 0.7.31 in FF 49.0.2 x64 on Win10 (Anniv) x64 
when Add-ons Manager is displayed
in new tab or window using PanelTab button 
or in new tab using FF Menu > 'Tools' > 'Add-ons' when 'Open in Sidebar' is disabled.
