### ISSUE TITLE
AIOS Icons disappear

### ISSUE THREAD

**Issue by pepegot1** [AddonLab/AiOS#122]
AIOS sidebar icons disappear. I can make them reappear by
view/toolbars/All in one sidebar toolbar, uncheck and then recheck,
but it does not last long and disappears again.

**Comment by RDL-github** [comment]
@pepegot1 

Others have found that these problems are transient and quick to fix, as described in  previous bug reports here. To save yourself and responders time and effort, please read other bug reports before opening new ones.

Meanwhile, please try (**all**) the following actions and post the result here.

1) **Disable** "Enable Sidebar Collapsing"
2) Enable the 'Sidebar Grippy' and use it, if required, to open and/or resize the AiOS sidebar.
3) Enable the 'Sidebar Switch' and use it, if required, to open the AiOS sidebar and/or 'AiOS Sidebar Toolbar'.

For details on how to do all those, please see the existing bug report:

sidebar tabs do not open at all · Issue #111 · AddonLab/AiOS · GitHub

https://github.com/AddonLab/AiOS/issues/111



See also: the AiOS extension homepage (support site) as linked to on the main AiOS page here.

The 'FAQ's, 'Features' and 'Screenshots' accessible from that site's toolbar are extremely helpful.

Please also note that AiOS 0.7.29 does not support the options to immediately open panels in new windows or new tabs instead of in the sidebar.

However, to do that with panels already open in the sidebar, you may still use 'Shift+Click' and 'Ctrl+Click' on the double-headed arrow in the AiOS sidebar header.
