### ISSUE TITLE
UpdatBookmark addon not works on Bookmarks sidebar

### ISSUE THREAD

**Issue by belteno** [AddonLab/AiOS#124]
Unfortunately UpdateBookmark addon (https://addons.mozilla.org/hu/firefox/addon/updatebookmark/) not works on Bookmarks sidebar (FF48). It works fine on Bookmarks Toolbar (top). Please check why not works. Thanks.

**Comment by ingowennemaring** [comment]
This has nothing to do with AiOS, because AiOS only improves the default sidebar layout and don't add sidebar panels. The bookmarks sidebar is a default part of Firefox and is not added by AiOS. Please contact the author of the extension „UpdateBookmark“. Maybe the comments on the extension page can help you, because there are notices for sidebar problems.
