### ISSUE TITLE
Close sidebar doesn't work with Sage

### ISSUE THREAD

**Issue by ruslanbes** [AddonLab/AiOS#126]
I'm using Sage RSS reader in the sidebar. The problem is that "Close sidebar" doesn't work on its page. Clicking it simply has no effect. Other buttons do work however.

![sage](https://cloud.githubusercontent.com/assets/4248022/18017726/4ef4b76a-6bd3-11e6-94cd-f0185982ba07.png)

Also "Close sidebar" does work on all other pages (Bookmarks, History, Addons and Page info). Firefox 48.0 , AiOS 0.7.30, Sage 1.5.4

**Comment by RDL-github** [comment]
@ruslanbes 

> I'm using Sage RSS reader in the sidebar. The problem is that "Close sidebar" doesn't work on its page. Clicking it simply has no effect. Other buttons do work however.
>
>Also "Close sidebar" does work on all other pages (Bookmarks, History, Addons and Page info). Firefox 48.0 , AiOS 0.7.30, Sage 1.5.4

I can confirm that I see the same things  for Sage (button doesn't work) and for Bookmarks, History, Addons and Page info (button does work) with AiOS 07.30 in FF48.0.1 x64 on Win 10 (Aniv) x64.

I also note that the close button has no effect when 'Scrapbook' is being displayed but it does when the built in 'Error Console' is displayed.

I am tempted to suspect that the button now works with all FF built-in sidebar features, but not with (?older?) extensions like Sage and Scrapbook.

I don't have enough time to sleep and to also test this further (eg in new test profile, or using another, diiferent, older extension in the sidebar).

Circumvention (obvious and silly, I'm afraid but it serves - I don't ever use that particular button myself): close the Sage panel by clicking twice on the bookmarks button.

**Comment by Klipper** [comment]
Same problem here with Echofon_unofficial, Scrapbook Plus, Feed Sidebar. You cannot close or open the sidebar att all. Not with the main toolbar button of AIO, not with the Sidebar switch, not with F4. Only way to close is first switching to I.E. Downloads or Bookmarks.  So probably every foreign add-on gets blocked currently (closing-opening the sidebar) 
Using Firefox 48.0.2 on Win10 AIOS 0.7.30
When reverting to 0.7.28 everything works again...

**Comment by RDL-github** [comment]
@Klipper:

>Same problem here with Echofon_unofficial, Scrapbook Plus, Feed Sidebar. You cannot close ***or open the sidebar att all. Not with the main toolbar button of AIO, not with the Sidebar switch, not with F4. Only way to close is first switching to I.E. Downloads or Bookmarks***. So probably every foreign add-on gets blocked currently (closing-opening the sidebar)
Using Firefox 48.0.2 on Win10 AIOS 0.7.30
When reverting to 0.7.28 everything works again... 

For me, closing Sage or Scrapbook with F4 or the 'sidebar switch' all work without problem.
Only use of the 'Close' button in the sidebar header fails to close the sidebar for those extensions.

However, like you, I do see that, once the sidebar showing Sage or Scrapbook is closed by clicking either F4 or the sidebar switch, then repeating that action only reveals the 'sidebar toolbar' but not the sidebar itself.  For FF built-in displays (bookmarks etc, as previously mentioned) the sidebar content display is toggled back on as expected.

By the way, all 'add-ons' are 'foreign'. Otherwise they would not be 'add-ons', which need to be added on.  So we can do without the 'foreign' bit. I'm not sure how best to describe FF 'built-in' things but, until someone gives me something better, "FF 'built-in..." is the best I can do.

**Comment by ingowennemaring** [comment]
Fixed in the next release.

**Comment by RDL-github** [comment]
Fixed for me by AiOS 0.7.31 in FF 49.0.2 x64 on Win10 (Anniv) x64
