### ISSUE TITLE
Symbol bar buttons open windows in FF48.0.2

### ISSUE THREAD

**Issue by Dirk-Ho** [AddonLab/AiOS#128]
Since updating to FF48.0.2 while choosing the sidebar content via menu works fine, swiching content via button in the all-in-one-sidebar symbol bar will open the requested content in a new window.

All the open ... in sidebar options are checked in the settings.

**Comment by RDL-github** [comment]
@Dirk-Ho 

>Since updating to FF48.0.2 while choosing the sidebar content via menu works fine, swiching content via button in the all-in-one-sidebar symbol bar will open the requested content in a new window.
>
>All the open ... in sidebar options are checked in the settings.

I don't see this at all, using AiOS 0.7.30 in FF48.0.2 x64 on Win 10 (Anniv) x64

However, for many, it was a problem when using AiOS version 0.7.28 and before in Firefox 48.0 etc.

**Important: do not update AiOS before reading the rest of this post.**

Please try (**all**) the following actions **in the same order as they are listed** and post the result here.

1) Disable "Enable Sidebar Collapsing"
2) Ensure you are using the latest version, 0.7.30, of AiOS.
3) Enable the 'Sidebar Grippy' and use it, if required, to open and/or resize the AiOS sidebar.
4) Enable the 'Sidebar Switch' and use it, if required, to open the AiOS sidebar and/or 'AiOS Sidebar Toolbar'.

For details on how to do (1), (3) and (4), please see the existing bug report:

Sidebar tabs do not open at all · Issue #111 · AddonLab/AiOS · GitHub

#111

See also: the AiOS extension homepage (support site) as linked to on the main AiOS page at the Mozilla Add-ons site.

The 'FAQ's, 'Features' and 'Screenshots' accessible from that AiOS homepage/support site's toolbar are extremely helpful.

Please also note that AiOS 0.7.30 does not support the options to immediately open panels in new windows or new tabs instead of in the sidebar.

However, to do that with panels already open in the sidebar, you may still use 'Shift+Click' and 'Ctrl+Click' on the double-headed arrow in the AiOS sidebar header.

**Comment by Dirk-Ho** [comment]
Hello,

sorry for the delayed response, I haven't been at my computer for the first half of the week.
When I started Firefox today, it updated AiOS and the issue was gone :-).

So thank you for looking into it, but it's obsolete now.
