### ISSUE TITLE
AiOS 0.7.30 rejected by Firefox 49.0.1

### ISSUE THREAD

**Issue by NotesTracker** [AddonLab/AiOS#134]
Was happily running AiOS v0.7.28 with Firefox 45.0.2 (reported as "up to date" under About Firefox).

Needed to do a plug-in check and was rejected with "not latest version of Firefox" error, therefore upgraded to Firefox v49.0.1 (on 02 October 2016).

Now find that AiOS v0.7.28 is now being rejected with "could not be verified for use in Firefox and has been disabled" error. Therefore tried to install AiOS v0.7.30 (had to override "prevented this site from asking you to install" dialog) then got "Firefox prevented this site from installing an unverified add-on" showstopper.

Went to about:config and changed xpinstall.signatures.required to false, but this didn't help.

What else can I try, or -- following https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox -- does AiOS have to be signed and re-issued before it will install in Firefox 49.0.1 ?

**Comment by RDL-github** [comment]
@NotesTracker 

> Now find that AiOS v0.7.28 is now being rejected with "could not be verified for use in Firefox and has been disabled" error. Therefore tried to install AiOS v0.7.30 (had to override "prevented this site from asking you to install" dialog) then got "Firefox prevented this site from installing an unverified add-on" showstopper.

I suspect that you may have installed and are trying to update AiOS from a site other than the official Mozilla add-ons site  (AMO for short)- most probably from 

All-in-One Sidebar :: Sidebar Extension for Mozilla Firefox :: firefox.eXXile.net
http://firefox.exxile.net/aios/index.php

It appears that AiOS 0.7.30 on that site is not signed.

If that could be your problem, please uninstall that version and instead install AiOS 0.7.30 from the official AMO site.

All-in-One Sidebar :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/all-in-one-sidebar/

That version is signed, as are all extensions hosted on AMO.

Please post the result here. If that does not solve your problem then, to help people to respond, please also include details on your operating system and version (eg Windows 10 x64 or x86/32) and whether you are using the 64-bit version of Firefox or, instead, the 32-bit version.

When you have successfully installed AiOS 0.7.30, please note that recent changes to Firefox have required some changes to AiOS. If you see problems with it, please:

1) Disable 'Sidebar Collapsing'.
2) Enable 'Sidebar Grippy' and, if necessary, use it to show the sidebar.
3) Enable 'Sidebar Switch' and, if necessary, use it to show the sidebar.

For details on how to do all that and some other useful information, see:

sidebar tabs do not open at all · Issue #111 · AddonLab/AiOS
https://github.com/AddonLab/AiOS/issues/111

**Comment by NotesTracker** [comment]
Dank, jetzt alles gut.
AiOS v0.7.30 is now installed (didn't even have to uninstall AiOS v0.7.28).

Since I followed a link and found myself at the unofficial developer site firefox.eXXile.net, and other people might fall into the same trap (bypassing the official add-on page), I would strongly recommend that the installer at the developer site either be replaced with the signed version or the linkbe changed to point to the official Mozilla site for the add-on.

**Comment by RDL-github** [comment]
@NotesTracker 

> Dank, jetzt alles gut.
AiOS v0.7.30 is now installed (didn't even have to uninstall AiOS v0.7.28).

Good. Glad to be of assistance.

No need for de-DE. I'm not the developer (ingo wennemaring) and my native tongue is en-GB :D 

>I followed a link in the sidebar itself to http://addonlab.com which was redirected to the unofficial developer site firefox.eXXile.net, so other people might fall into this same trap (which bypasses the official add-on page).

That is the developer's homepage. That site contains a great deal of helpful information and is not in any way unofficial. It also used to host a very useful forum which had to be closed because of extensive spamming (hence the bug reporting function moved to this site).

The link you used there is sometimes used for development/test versions. Immediately under that link is one to the AMO page for AiOS.

Mozilla always firmly recommends that you download and/or install add-ons from AMO unless there is a specific reason to do otherwise.

Development (test) versions of Firefox do not require add-ons to be signed. There is also an official "unbranded" (but en-US only) version of Firefox which allows users to install unsigned add-ons. 

>Therefore I would strongly recommend that the installer at the developer site either be replaced with the signed version or the installer link be replaced with the hyperlink that points to the official Mozilla site for the add-on.

See above.

Regards

RDL
