### ISSUE TITLE
AiOS 0.7.30 breaks "Add-Ons Manager" window appearance in FireFox 49.0.1

### ISSUE THREAD

**Issue by paulescobar** [AddonLab/AiOS#136]
OS: Windows 10 Pro 64 Bit
Device: 7.9" Mi Pad 2 Tablet
FireFox: 49.0.1
AiOS: 0.7.30

This is what my "Add-Ons Manager" window looks like...BEFORE I install AiOS:
![sidebar disabled](https://cloud.githubusercontent.com/assets/22924037/19500890/35680980-956f-11e6-85cf-6a4d31928d5a.png)

This is what my "Add-Ons Manager" window looks like...AFTER I install AiOS:
![sidebar enabled](https://cloud.githubusercontent.com/assets/22924037/19500891/356b52ac-956f-11e6-9ec9-a4666fd91500.png)

As you can see, your add-on causes the "Add-Ons Manager" to look compressed and ugly.
I can only restore its appearance by disabling AiOS.

I would like to note, I am talking about the "Add-Ons Manager" in its normal tab display (not sidebar display). So even though I disable "Add-Ons" in the AiOS options, it still breaks the general appearance of this window.

I have tried all sorts of settings combinations. I can't get the normal appearance of "Add-Ons Manager" window back while AiOS is installed.

**Comment by paulescobar** [comment]
I just tested on a fresh copy of FireFox 49.0.1 (no add-ons or settings modified).
I have also tested on both tablets & widescreen laptops.

The same problem occurs.
AIOS breaks the GUI of the AddOns manager window.

**Comment by Whisker72** [comment]
Yep, exactly the same problem here: Normal PC with Win7 Ultimate (x64), Firefox 49.0.2 and AiOS 0.7.28.

Add-Ons Manager looks compressed in an ugly way like in the example above, and as soon as I deactivate AiOS, it looks like it should i.e. in the "Before"-Picture above.

As far as I remember it could even go even farther back than AiOS 0.7.28, it just didn't really bother me that much if everything else works (and still doesn't, tbh). On the other hand, I don't mind if it gets fixed at some time, but I personally wouldn't rate it high-priority because it just doesn't look that great, but I can live with that.

**Comment by paulescobar** [comment]
To all,

Here is a workaround solution. 
This way you can use the proper-looking 'Add-Ons Manager', and AIOS. 

AIOS is breaking is the following URL:
`about:addons`

This is the URL used by toolbar buttons & FireFox top level menu's to access the 'Add-Ons Manager' window.

Instead, you can access using the following URL:
`about:addons?entrypoint=menupanel`

You can add this URL to a bookmark or a custom toolbar button. You can see, it presents the 'Add-Ons Manager' window properly. This way, you can also see all the improvement tweaks other add-ons like "Classic Theme Restorer' perform on the window.

Hopefully AIOS can be fixed in the future. But right now, I created a toolbar button (via Custom Button) to access my Add-On window properly, while still getting full functionality of AIOS.

**Comment by ingowennemaring** [comment]
This issue is a duplication of #102. The bug will be fixed in the next version.
