### ISSUE TITLE
AoOS Toolbar Missing

### ISSUE THREAD

**Issue by junkyard1978** [AddonLab/AiOS#145]
Hadnt used my PC for 2 weeks over Xmas as I was away so turned it off. Upon rebooting it, my AiOS toolbar has disappeared and despite going through every menu in FF and AiOS options, I cannot get it back. I have tried with the Switch and Grippy on and off and one on/one off even moved the sidebar to opposite side of the screen but no toolbar. Everything else works fantastically as always but I need my toolbar. Have searched all over for any help but most of the issues seem to be the sidebar not opening which is not the case with my setup. Help please

**Comment by gazzawazza** [comment]
What happens if you right-click on the FF menu button and review the available toolbars?

![aios toolbar in firefox toolbar list](https://cloud.githubusercontent.com/assets/3268066/21598014/2801ac10-d14c-11e6-909a-932e69e14b6d.PNG)

Is there an AiOS entry?

If so, is it ticked?

I've finding that fairly regularly my AiOS sidebar just disappears - unchecking rechecking its toolbar in the toolbar list makes it active again.

You've implied too that AiOS is still available in your add-ons list. Could you confirm the version and what version of FF you're running?


Thanks,

Gary

**Comment by junkyard1978** [comment]
Yeah, had checked that and the AiOS toolbar is checked. In every option I can find, Tools, View, options etc the toolbar is checked and have unchecked, closed FF, reopened FF, checked again then reopened all to no avail. Using FF v 50.1.0 & vers 0.7.31 of AiOS. I downgraded both AiOS and FF to older versions but same problem. Hate doing a reset as I lose all my extension preferences & last FEBE back up I have seems to be when error started. Absolutely love AiOS and is always first extension I add. Took me ages to get my Toolbar just right.

Thanks

**Comment by gazzawazza** [comment]
hi mate.

I hear your frustration.

I'd avoid a reset for the time being, though you might need to embrace it eventually.

My thoughts now would be:

- look at recent changes which coincided with loss of normal AiOS behaviour.
- I'd like to exclude a conflicting add-on (this really can happen), so try disabling all add-ons but AiOS and see if odd behaviour is replicated.
- try installing "addons recent updates" by infocatcher - this allows you to filter by x number of days and show which add-ons got updated (once installed, go the add-on's options and down the bottom you can specify the number of days to filter by)
- could you explain your comment

"...last FEBE back up I have seems to be when error started"?

Does this mean that prior to that extension backup, AiOS behaviour was ok? Can't you roll back to before that time then?
- you know you can import and export AiOS settings? Maybe you could export your current configuration, then restore defaults? Test whether AiOS returns to normal behaviour then import settings, in the off chance you can recover your configuration? Obviously  I can't guarantee that any issues which might be contributing to your problems won't get exported/imported but it's worth trying as a test.
- just to be clear, can you go into AiOS options? i.e. the add-on isn't fundamentally damaged?
- another thought: have you tried any of the AiOS keyboard shortcuts? Perhaps you could force something that way? F4 hides/exposes sidebar
- if the above don't throw anything up, I can only conclude something fundamental corrupted - look for any recorded firefox crashes around the time you suspect AiOS started misbehaving. Use "about:crashes" for clues. I suggest using this, again, to try and pinpoint what could have happened. If you've taken backups, you could try rolling back to before then.
- I actually use mozbackup to backup the entirety of my FF profile. I normally do this before updating firefox. It's entirely sensible to back up your extensions but sometimes you might just want to roll back to a 'safe ', known, stable installation of firefox, etc.
- You might also (just as a global precaution) run a full chkdsk (i.e. check for bad sectors).

sorry if you've done all this btw.


Cheers,

Gary

**Comment by junkyard1978** [comment]
Man, thanks for all your help and speedy replies on this and I have solved my problem. It seems the problem was a recent update to the extension Tree Style Tabs which I use to to place the FF tabs on the left handside along with AiOS. It seems the last update to TST must have been corrupted and somehow this affected AiOS. I deleted TST, shut down FF, reopened it and reinstalled TST and bingo, my AiOS toolbar is back for all the world to see.

I think your use of Mozbackup and doing a back up before any FF update will now be my way to go. I had to eliminate each extension manually to see which one was affecting the Toolbar and having 40 extensions and getting to  T" took awhile.

Again, great support and thank you very much, Gary.

Cheers

**Comment by gazzawazza** [comment]
Ah awesome. Really glad you found the issue. Happy to help too.

Most of the time when I'm troubleshooting I look for a change that coincided with the issue being experienced.

Painful though, when you have to wade through all your extensions! That's why the recent updates add-on I mentioned can be very helpful at creating a shortlist of possible culprits. I've got 28 active extensions, so know how tedious it is to shut them all down, to exclude possibilities.

Well done on your patience.

Yeah, mozbackup still seems to work fine. Very simple - just backs up literally everything in your profile. Just make sure you back up to a completely separate physical location. You might also consider backing up settings from key extensions too (now and then), just in case you needed to do a clean installation of firefox and wanted/needed a clean profile. I did this once and my mozbackup file dropped from 115MB to 25MB. In this scenario, depending on how heavily you use bookmarks, you'd want an independent backup of those (CTRL+B for bookmark library, then "import and export" then "backup". Maybe think about your saved passwords / login credentials, if you use them.

All the best,

Gary

**Comment by Thepipe** [comment]
I'm having the same problem - AIOS does not appear.

I'm using FF 51.0b14 (32-bit).  I am able to access AIOS options.  I've tried the following. with no luck:
• Made changes to AIOS settings.
• Disabled recently installed/updated extensions 
• Backed up AIOS settings, then removed and reinstalled AIOS
• Ensured AIOS is "checked" in list of visible sidebars

**Comment by gazzawazza** [comment]
**************************************************************************
> I'm having the same problem - AIOS does not appear.

I'm using FF 51.0b14 (32-bit). I am able to access AIOS options. I've tried the following. with no luck:
• Made changes to AIOS settings.
• Disabled recently installed/updated extensions
• Backed up AIOS settings, then removed and reinstalled AIOS
• Ensured AIOS is "checked" in list of visible sidebars

> 
**************************************************************************
Hi @Thepipe 

Sorry to hear this.

Sounds like you've tried the main things.

You too are going to have to think back to when it last worked and review any changes (as a starting point).

Do you have any backups you can roll back to (might be the quickest troubleshooting/solution)? If you do, just make a note of any add-ons you've added since + backup your bookmarks and login credentials (password exporter by justin scott works just fine for me).

**I've just noticed that you're using a Firefox beta though - perhaps you need to flag it with the dev and log as a bug?**

**If so, I'd start a new thread as this one involved a FF public release.**

**Maybe there's an AiOS beta build which deals with FF 51 changes?**

Just a few crude checks to finish:

1. I know you've said you checked that AiOS is checked/active as a visible toolbar - did you uncheck then recheck?

1. Try F4 too.

1. Have you tried setting AiOS settings to defaults

1. try disabling **all** addons except AiOS (tedious I know)

1. Try a new profile and installing AiOS solely.

Making a new profile isn't as painful as it sounds - make a shortcut to the firefox executable and just insert "-p" (without quotes) at the end of the target path. Then just make a new profile - name it sanely (as this alphanumeric name will appear as part of the profile folder name) and go for it.



Regards,

Gary

**Comment by Thepipe** [comment]
I was just about to reply that it isn't worth my time, jumping through hoops to figure out what may have caused the problem (it really could take a lot of time).  But, in scanning your lengthy list of troubleshooting options, I decided to try pressing F4 and BINGO!  AIOS is back!

Sadly, I believe many people see the multitude of troubleshooting possibilities and also decide it's not worth it and just live without the add-on.  I was close to doing that.  Luckily, I found the answer.

Thanks!

**Comment by gazzawazza** [comment]
wow!

Good stuff!

Glad the F4 worked.

Troubleshooting is painful, really because you have to be methodical and working out extension issues is annoying because users may well have lots of add-ons.

Really pleased you got it worked. I expect the dev is pleased too - kinda get feeling that each FF release potentially breaks stuff.


Cheers,

Gaz

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php

**Comment by gazzawazza** [comment]
@ingowennemaring just wanted to say thank you for everything you've put into AiOS

I've <3 your message out of respect, not because I like the AiOS is no more (obviously).
